# Travis CI

language: php

php:
- 5.3
- 5.4
- 5.5
- 7.0
- hhvm
- nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

## DISABLED because of Travis CI Build Error || script: phpunit tests/LobbyInstall.php
