<?php
/* A Sample Configuration File */
/* !! DO NOT EDIT THIS FILE !! */
$LC_config = array(
 'host' => '',
 'port' => '',
 'user' => '',
 'pass' => '',
 'db' => '',
 'key' => '',
 'prefix' => 'l_'
);
$LC->debug(false);
/* !! DO NOT EDIT THIS FILE !! */
?>