<?php
/* The Configuration File - Be careful while editing */
return array(
  'db' => array(
    'host' => 'localhost',
    'port' => '3306',
    'username' => 'root',
    'password' => 'backstreetboys',
    'dbname' => 'lobbyLocal',
    'prefix' => 'l_'
  ),
  /**
   * The GLOBAL unique ID of YOUR Lobby installation
   */
  'lobbyID' => '4lqmSC3SaCrolEcgTlSyjyhDzyBelHUfTbsCDmkEOCT06',
  /**
   * A Secure Identity of YOUR Lobby Installation.
   * Never reveal it TO ANYONE
   */
  'secureID' => 'a3b0b216db35bb3838c0ebe997406d84693fd633ff0c2c3dbb1f09f390456907d1055af452f9d0a70a00e9adbb6fb7e9b0e620f3d196c6fd379d5d2ef3cc8794',
  'debug' => true
);
/* DO NOT EDIT THIS FILE IF YOU DON'T KNOW WHAT YOU'RE DOING - Subin */
?>
