window.clog=function(msg){console.log(msg);};window.lobby={load_callbacks:[],load:function(callback){lobby.load_callbacks.push(callback);},load_init:function(){if(typeof lobby.load_script_url!="undefined"){var d=document,o=d.createElement('script');o.type="text/javascript";o.async=true;o.src=lobby.load_script_url;o.addEventListener('load',function(e){setTimeout(function(){$.each(lobby.load_callbacks,function(i,callback){callback();});lobby.load_callbacks=[];},225);},false);d.getElementsByTagName('head')[0].appendChild(o);}},mod:{},notify:{}};if(typeof window.lobbyExtra!="undefined"){window.lobby=$.extend(window.lobbyExtra,lobby);}
$(function(){lobby.load_init();});lobby.curLoc=window.location.protocol+"//"+window.location.host+window.location.pathname;$(document).mouseup(function(e){$(".c_c").each(function(i){if(!$(this).is(e.target)&&$(this).find(e.target).length===0||e.target==$("body")[0]){$(this).hide();}});});lobby.ajax=function(fileName,options,callback,appID){callback=typeof callback=="function"?callback:function(){};if(typeof options==="object"){var options=$.param(options);}
if(appID!=false){var options=$.param({"s7c8csw91":appID})+"&"+options;}
var options=$.param({"cx74e9c6a45":fileName,"csrf_token":lobby.csrf_token})+"&"+options;var requestURL=lobby.url+"/includes/lib/lobby/ajax/ajax.php";$.post(requestURL,options,function(data){callback(data);});};lobby.saveOption=function(key,value,callback){var callback=typeof callback=="function"?callback:function(){};var requestURL=lobby.url+"/includes/lib/lobby/ajax/saveOption.php";if(key==""||value==""){callback("bad");}else{$.post(requestURL,{"key":key,"value":value,"csrf_token":lobby.csrf_token},function(data){callback(data);}).error(function(){callback("bad");});}};lobby.redirect=function(path){window.location=lobby.url+path;};lobby.toast=function(message,displayLength,className,completeCallback){Vel=function(html,css,options){$(html).animate(css,options);}
className=className||"";var container=document.getElementById('toast-container');if(container===null){container=document.createElement('div');container.id='toast-container';document.body.appendChild(container);}
var newToast=createToast(message);if(message){container.appendChild(newToast);}
newToast.style.top='35px';newToast.style.opacity=0;Vel(newToast,{"top":"0px",opacity:1},{duration:300,easing:'easeOutCubic',queue:false});var timeLeft=displayLength;var counterInterval=setInterval(function(){if(newToast.parentNode===null)
window.clearInterval(counterInterval);if(!newToast.classList.contains('panning')){timeLeft-=20;}
if(timeLeft<=0){Vel(newToast,{"opacity":0,marginTop:'-40px'},{duration:375,easing:'easeOutExpo',queue:false,complete:function(){if(typeof(completeCallback)==="function")
completeCallback();this[0].parentNode.removeChild(this[0]);}});window.clearInterval(counterInterval);}},20);function createToast(html){var toast=document.createElement('div');toast.classList.add('toast');if(className){var classes=className.split(' ');for(var i=0,count=classes.length;i<count;i++){toast.classList.add(classes[i]);}}
if(typeof HTMLElement==="object"?html instanceof HTMLElement:html&&typeof html==="object"&&html!==null&&html.nodeType===1&&typeof html.nodeName==="string"){toast.appendChild(html);}
else if(html instanceof jQuery){toast.appendChild(html[0]);}
else{toast.innerHTML=html;}
var hammerHandler=new Hammer(toast,{prevent_default:false});hammerHandler.on('pan',function(e){var deltaX=e.deltaX;var activationDistance=80;if(!toast.classList.contains('panning')){toast.classList.add('panning');}
var opacityPercent=1-Math.abs(deltaX / activationDistance);if(opacityPercent<0)
opacityPercent=0;Vel(toast,{left:deltaX,opacity:opacityPercent},{duration:50,queue:false,easing:'easeOutQuad'});});hammerHandler.on('panend',function(e){var deltaX=e.deltaX;var activationDistance=80;if(Math.abs(deltaX)>activationDistance){Vel(toast,{marginTop:'-40px'},{duration:375,easing:'easeOutExpo',queue:false,complete:function(){if(typeof(completeCallback)==="function"){completeCallback();}
toast.parentNode.removeChild(toast);}});}else{toast.classList.remove('panning');Vel(toast,{left:0,opacity:1},{duration:300,easing:'easeOutExpo',queue:false});}});return toast;}};