<?php
/* The Configuration File - Be careful while editing */
return array(
  'db' => array(
    'type' => 'mysql',
    'host' => '127.0.0.1',
    'port' => '3306',
    'username' => '',
    'password' => '',
    'dbname' => '',
    'prefix' => 'l_'
  ),
  /**
   * The GLOBAL unique ID of YOUR Lobby installation
   */
  'lobbyID' => '',
  /**
   * A Secure Identity of YOUR Lobby Installation.
   * Never reveal it TO ANYONE
   */
  'secureID' => '',
  'debug' => false
);
/* DO NOT EDIT THIS FILE IF YOU DON'T KNOW WHAT YOU'RE DOING - Subin */
?>
